# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e091e775d7001bf9fe522e3fe88dced6969bb57ea821bf206825b8ddae35def6cadeb77ef1ccec575940236de6b7fb8db9193db4fadec6475c0ac79dc24f9e4

test:
  secret_key_base: 40165a7e50a21118bf350aa790cf65283571d5e54bd7062f1ca09fba0b09359e65ad3d968ebd38999d65ed87c18c3c3058b84de23f02cbf3dc765e39a97520ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
